### ISSUE TITLE
Interested in improve this?

### ISSUE THREAD

**Issue by matbrgz** [mattdp/mnemonic#32]
We are a garage startup looking for a great CRM tool, did you plan to back work on this project with someone is interested?

**Comment by mattdp** [comment]
@MatheusRV Hi Matheus, I don't plan to pick up work on this again, but I've spent a lot of time looking at CRMs - want to tell me a bit about what you want a CRM for? I can recommend if I know any cheap/free options that might solve your problem :)

**Comment by matbrgz** [comment]
Ow yes, I'm looking a solution to integrate with spree (rails)

**Comment by mattdp** [comment]
@MatheusRV Sorry, I don't know anything that integrates there specifically. For a simple, low price CRM I really liked lessannoyingcrm.com but I don't know if their API meets your needs.

**Comment by matbrgz** [comment]
Tks
